=head1 NAME

rapid-photo-downloader - downloads, renames and backs up photos and videos from cameras, phones,
memory cards and other devices

=head1 SYNOPSIS

B<rapid-photo-downloader> [options]

Options:

    -h, --help
    --version
    --detailed-version
    -v, --verbose
    --debug
    -e, --extensions
    -a {on,off}, --auto-detect {on,off}
    -t {on,off}, --this-computer {on,off}
    --this-computer PATH
    --photo-destination PATH
    --video-destination PATH
    -b {on,off}, --backup {on,off}
    --backup-auto-detect {on,off}
    --photo-backup-identifier FOLDER
    --video-backup-identifier FOLDER
    --photo-backup-location PATH
    --video-backup-location PATH
    --ignore-other-photo-file-types
    --thumbnail-cache {on,off}
    --delete-thumbnail-cache
    --reset

=head1 DESCRIPTION

B<Rapid Photo Downloader> imports photos and videos from cameras, phones,
memory cards and other devices at high speed. It can be configured to
rename photos and videos with meaningful filenames you specify. It can also
back up photos and videos as they are downloaded. It downloads from and backs
up to multiple devices simultaneously.

Unique to Rapid Photo Downloader is its timeline feature,
allowing you to group photos and videos based on how much time elapsed
between consecutive shots. You can use this to quickly identify photos
and videos taken at different periods in a single day or over consecutive
days.

=head1 OPTIONS

=over

=item B<-h, --help>

Show help message and exit.

=item B<--version>

Displays information about the currently installed version and exits.

=item B<--detailed-version>

Displays information about the currently installed version and its libraries and exits.

=item B<-v, --verbose>

Displays program information on the command line as the program runs.

=item B<---debug>

Displays debugging information on the command line as the program runs

=item B<-e, --extensions>

Displays image file extensions the program recognizes and exits.

=item B<-a {on,off}, --auto-detect {on,off}>

Turn on or off the automatic detection of devices from which to download, 
overwriting existing program preferences.

=item B<-t {on,off}, --this-computer {on,off}>

Turn on or off downloading from this computer, overwriting existing program preferences.

=item B<--this-computer-location PATH>

The PATH on this computer from which to download, overwriting existing program 
preferences.

=item B<--photo-destination PATH>

Sets the PATH where photos will be downloaded to, overwriting existing program
preferences.

=item B<--video-destination PATH>

Sets the PATH where videos will be downloaded to, overwriting existing program
preferences.

=item B<-b {on,off}, --backup {on,off}>

Turns on or off the backing up of photos and videos while downloading, overwriting
existing program preferences.

=item B<--backup-auto-detect {on,off}>

Turns on or off the automatic detection of backup devices, overwriting
existing program preferences.

=item B<--photo-backup-identifier FOLDER>

Sets the FOLDER in which backups are stored on the automatically detected photo backup 
device, with the folder's name being used to identify whether or not the device
is used for backups. For each device you wish to use for backing up photos to, 
create a folder on it with this name. Overwrites existing program preferences.

=item B<--video-backup-identifier FOLDER>

Sets the FOLDER in which backups are stored on the automatically detected video backup 
device, with the folder's name being used to identify whether or not the device
is used for backups. For each device you wish to use for backing up videos to, 
create a folder on it with this name. Overwrites existing program preferences.

=item B<--photo-backup-location PATH>

Sets the PATH where photos will be backed up when automatic detection of backup devices
is turned off. Overwrites existing program preferences.

=item B<--video-backup-location PATH>

Sets the PATH where videos will be backed up when automatic detection of backup devices
is turned off. Overwrites existing program preferences.

=item B<--ignore-other-photo-file-types>

Do not download photos with the following extensions: TIF, TIFF and MPO.

=item B<--thumbnail-cache {on,off}>

Turns on or off use of the Rapid Photo Downloader Thumbnail Cache. Turning it off does not
delete existing cache contents.

=item B<--delete-thumbnail-cache>

Deletes all thumbnails in the Rapid Photo Downloader Thumbnail Cache, and exits.

=item B<--reset>

Resets all program settings to their default values, deletes all thumbnails in the Thumbnail
cache, forgets which files have been previously downloaded, and exits.

=back

=head1 AUTHORS

B<Rapid Photo Downloader> was written by Damon Lynch <damonlynch@gmail.com>.

This manual page was written by Damon Lynch.

=head1 COPYRIGHT

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 3, or (at your option) any
later version.

On Debian GNU/Linux systems, the complete text of the GNU General
Public License can be found in `/usr/share/common-licenses/GPL'.

=cut

