# -*- coding: latin1 -*-
VERTICAL_CONTROL_LABEL_SPACE = CONTROL_LABEL_SPACE = 12
CONTROL_IN_TABLE_SPACE = 6
WINDOW_BORDER_SPACE = 12
NESTED_CONTROLS_SPACE = 24
VERTICAL_CONTROL_SPACE = 18
VERTICAL_GROUP_SPACE = 24
HORIZONTAL_GROUP_SPACE = 24
