=head1 NAME

rapid-photo-downloader - gets images from camera memory cards and other devices

=head1 SYNOPSIS

rapid-photo-downloader

=head1 DESCRIPTION

B<Rapid Photo Downloader> downloads photos from memory cards and Portable
Storage Devices, providing a variety of options for subfolder creation,
image renaming and backup. It can download images from more than one memory
card in parallel.

It is designed for use on the GNOME 2 Desktop.

=head1 BUGS

Please report bugs at https://bugs.launchpad.net/rapid.

=head1 AUTHORS

B<Rapid Photo Downloader> was written by Damon Lynch <damonlynch@gmail.com>.

This manual page was written by Damon Lynch.

=head1 COPYRIGHT

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2, or (at your option) any
later version.

On Debian GNU/Linux systems, the complete text of the GNU General
Public License can be found in `/usr/share/common-licenses/GPL'.

=cut

