#  SPDX-FileCopyrightText: 2026 Damon Lynch <damonlynch@gmail.com>
#  SPDX-License-Identifier: GPL-3.0-or-later

from collections import defaultdict

from raphodo.constants import StockAccent

colors = (
    ("blue", StockAccent),
    ("teal", "#2190a4"),
    ("green", "#3a944a"),
    ("yellow", "#c88800"),
    ("orange", "#ed5b00"),
    ("red", "#e62d42"),
    ("pink", "#d56199"),
    ("purple", "#9141ac"),
    ("slate", "#6f8396"),
    ("adwaita", StockAccent),
    ("yaru", "#e95420"),
    ("yaru-dark", "#e95420"),
    ("yaru-bark", "#787859"),
    ("yaru-bark-dark", "#787859"),
    ("yaru-sage", "#657b69"),
    ("yaru-sage-dark", "#657b69"),
    ("yaru-olive", "#4b8501"),
    ("yaru-olive-dark", "#4b8501"),
    ("yaru-viridian", "#03875b"),
    ("yaru-viridian-dark", "#03875b"),
    ("yaru-prussiangreen", "#308280"),
    ("yaru-prussiangreen-dark", "#308280"),
    ("yaru-blue", "#0073e5"),
    ("yaru-blue-dark", "#0073e5"),
    ("yaru-purple", "#7764d8"),
    ("yaru-purple-dark", "#7764d8"),
    ("yaru-magenta", "#b34cb3"),
    ("yaru-magenta-dark", "#b34cb3"),
    ("yaru-red", "#da3450"),
    ("yaru-red-dark", "#da3450"),
    ("mint-l", "#92b372"),
    ("mint-l-aqua", "#6cabcd"),
    ("mint-l-blue", "#5b73c4"),
    ("mint-l-brown", "#aa876a"),
    ("mint-l-dark", "#92b372"),
    ("mint-l-dark-aqua", "#6cabcd"),
    ("mint-l-dark-blue", "#5b73c4"),
    ("mint-l-dark-brown", "#aa876a"),
    ("mint-l-darker", "#92b372"),
    ("mint-l-darker-aqua", "#6cabcd"),
    ("mint-l-darker-blue", "#5b73c4"),
    ("mint-l-darker-brown", "#aa876a"),
    ("mint-l-darker-grey", "#9d9d9d"),
    ("mint-l-darker-orange", "#db9d61"),
    ("mint-l-darker-pink", "#c76199"),
    ("mint-l-darker-purple", "#8c6ec9"),
    ("mint-l-darker-red", "#c15b58"),
    ("mint-l-darker-sand", "#c8ac69"),
    ("mint-l-darker-teal", "#5aaa9a"),
    ("mint-l-dark-grey", "#9d9d9d"),
    ("mint-l-dark-orange", "#db9d61"),
    ("mint-l-dark-pink", "#c76199"),
    ("mint-l-dark-purple", "#8c6ec9"),
    ("mint-l-dark-red", "#c15b58"),
    ("mint-l-dark-sand", "#c8ac69"),
    ("mint-l-dark-teal", "#5aaa9a"),
    ("mint-l-grey", "#9d9d9d"),
    ("mint-l-orange", "#db9d61"),
    ("mint-l-pink", "#c76199"),
    ("mint-l-purple", "#8c6ec9"),
    ("mint-l-red", "#c15b58"),
    ("mint-l-sand", "#c8ac69"),
    ("mint-l-teal", "#5aaa9a"),
    ("mint-x", "#78aeed"),
    ("mint-x", "#9ab87c"),
    ("mint-x-aqua", "#6cabcd"),
    ("mint-x-aqua", "#78aeed"),
    ("mint-x-blue", "#5b73c4"),
    ("mint-x-blue", "#78aeed"),
    ("mint-x-brown", "#78aeed"),
    ("mint-x-brown", "#aa876a"),
    ("mint-x-grey", "#78aeed"),
    ("mint-x-grey", "#9d9d9d"),
    ("mint-x-orange", "#78aeed"),
    ("mint-x-orange", "#db9d61"),
    ("mint-x-pink", "#78aeed"),
    ("mint-x-pink", "#c76199"),
    ("mint-x-purple", "#78aeed"),
    ("mint-x-purple", "#8c6ec9"),
    ("mint-x-red", "#78aeed"),
    ("mint-x-red", "#c15b58"),
    ("mint-x-sand", "#78aeed"),
    ("mint-x-sand", "#c8ac69"),
    ("mint-x-teal", "#5aaa9a"),
    ("mint-x-teal", "#78aeed"),
    ("mint-y", "#35a854"),
    ("mint-y-aqua", "#1f9ede"),
    ("mint-y-blue", "#0c75de"),
    ("mint-y-dark", "#35a854"),
    ("mint-y-dark-aqua", "#1f9ede"),
    ("mint-y-dark-blue", "#0c75de"),
    ("mint-y-dark-grey", "#70737a"),
    ("mint-y-dark-orange", "#ff7139"),
    ("mint-y-dark-pink", "#e54980"),
    ("mint-y-dark-purple", "#8c5dd9"),
    ("mint-y-dark-red", "#e82127"),
    ("mint-y-dark-sand", "#c5a07c"),
    ("mint-y-dark-teal", "#199ca8"),
    ("mint-y-grey", "#70737a"),
    ("mint-y-orange", "#ff7139"),
    ("mint-y-pink", "#e54980"),
    ("mint-y-purple", "#8c5dd9"),
    ("mint-y-red", "#e82127"),
    ("mint-y-sand", "#c5a07c"),
    ("mint-y-teal", "#199ca8"),
)
GnomeAccentColor = defaultdict(lambda: StockAccent)
for k, v in colors:
    GnomeAccentColor[k] = v
